### ISSUE TITLE
Installing yarn add usb

### ISSUE THREAD

**Issue by ruzrulit** [tessel/node-usb#180] opened 2017-05-06 16:29 UTC
Hello,

could you please help me with installation. The error is:

> node_modules\usb\src\binding\usb_bindings.node" (not found)

Also it says that i can download from here

[https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v51-win32-x64.tar.gz](https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v51-win32-x64.tar.gz)

but there is only v48.

How can i fix it?

Thanx in advance!

**Comment by kevinmehall** [comment] 2017-05-06 17:21
Duplicate of #163 -- There are no binary releases for Node 7.x yet, so use Node 6.x or compile from source.

**Closed by kevinmehall** 2017-05-06 17:21 UTC

**Comment by ruzrulit** [comment] 2017-05-07 13:50
Thanx a lot!
