### ISSUE TITLE
Can't build libusb

### ISSUE THREAD

**Issue by hannfes** [tessel/node-usb#151] opened 2016-11-14 09:28 UTC
When I rebuild usb for electron, I get a build error.
`electron-gyp node-gyp rebuild --target=0.26.0 --arch=ia32 --dist-url=https://atom.io/download/atom-shell
`
> error C2011: 'timespec': 'struct' type redefinition (compiling source file ..\libusb\libusb\core.c). 

Always the same error in different files. How can I solve this? Thanks in advance.

(I use Windows 10 with Visual Studio 2015 installed)

**Comment by kevinmehall** [comment] 2017-02-13 06:56
Duplicate of #141, #109, and #162

**Closed by kevinmehall** 2017-02-13 06:56 UTC
