### ISSUE TITLE
NODE_MODULE_VERSION conflict

### ISSUE THREAD

**Issue by burakkilic** [tessel/node-usb#181] opened 2017-05-20 17:21 UTC
Hello,

I was using node-usb without error with Node 5 but after installing Node 7, I am getting errors.

    Error: The module '/node_modules/usb/src/binding/usb_bindings.node'
    was compiled against a different Node.js version using
    NODE_MODULE_VERSION 51. This version of Node.js requires
    NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
    the module (for instance, using `npm rebuild` or`npm install`). 

I tried to re-compile but couldn't succeed. 

How can I fix that?

**Comment by kevinmehall** [comment] 2017-05-20 18:08
Duplicate of #163.

`master` branch should be able to compile for Node 7. See [toolchain setup instructions here](https://github.com/nodejs/node-gyp#installation). Linux also requires `libudev-dev`. If that fails, post what you tried and the error message.

**Closed** 2017-05-20 18:09 UTC
