### ISSUE TITLE
Any plan to upgrade libusb to the latest version?

### ISSUE THREAD

**Issue by JavaCS3** [tessel/node-usb#245] opened 2018-05-29 14:17 UTC

**Comment by pumano** [comment] 2018-06-09 13:58
It should be updated because `usb` not contains pre-compiled binary for node 10

**Comment by kevinmehall** [comment] 2018-06-09 20:19
Duplicate of #161 

@pumano Node version is not related to libusb version. If NAN supports Node 10 without changes, it just takes adding it to the Travis and Appveyor config and making a release.

**Closed** 2018-06-09 20:20 UTC
