### ISSUE TITLE
Latest release (1.7.0) incompatible with Ubuntu 120.04

### ISSUE THREAD

**Issue by systemmonkey42** [tessel/node-usb#423] opened 2021-05-05 06:57 UTC
The latest release downloads prebuild binaries which require a newer version of GLIBC.

```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /.../node_modules/usb/build/Release/usb_bindings.node)
```
Release 1.6.5 works ok.   

The package.json install script performs the prebuild-install and on failure *would* invoke node-gyp, however it
is succeeding in installed the wrong binaries.

**Comment by thegecko** [comment] 2021-05-05 18:29
Thanks @systemmonkey42 , this is a duplicate of #417

**Closed by thegecko** 2021-05-05 18:29 UTC
