### ISSUE TITLE
LIBUSB_ERROR_NOT_FOUND on MacOS when trying to open a device.

### ISSUE THREAD

**Issue by jmbldwn** [tessel/node-usb#61] opened 2014-12-24 21:06 UTC
Kinda takes the fun out of it.

I'm able to find devices just fine:

> var usb = require('usb');
> var dev = usb.findByIds(0x132b, 0x2101);
> dev
{ busNumber: 20,
  deviceAddress: 12,
  deviceDescriptor: 
   { bLength: 18,
     bDescriptorType: 1,
     bcdUSB: 272,
     bDeviceClass: 255,
     bDeviceSubClass: 0,
     bDeviceProtocol: 0,
     bMaxPacketSize0: 16,
     idVendor: 4907,
     idProduct: 8449,
     bcdDevice: 256,
     iManufacturer: 1,
     iProduct: 2,
     iSerialNumber: 0,
     bNumConfigurations: 1 } }

... but trying to open the device fails:

> dev.open();
Error: LIBUSB_ERROR_NOT_FOUND
    at Device.Object.defineProperty.get (/Users/jim/node_modules/usb/usb.js:45:45)
    at Device.usb.Device.open (/Users/jim/node_modules/usb/usb.js:30:16)
    at repl:1:5
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)

libusb1.0.19 installed.  Also tried libusb1.0.8.  Same answer.

Ideas?

**Comment by jtbonhomme** [comment] 2015-01-08 08:01
Same issue for me:
OSX Lion 10.7.5
```
$  uname -a
Darwin new-host.home 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64
$  node -v
v0.10.33
$  npm -v
1.4.28
```

**Comment by jmbldwn** [comment] 2015-01-08 15:31
Here’s my workaround.  I can’t remember how I stumbled across this, but it seems to work for me.  Calling the semi-private __open() and __claimInterface() functions before the public open function seems to jiggle it into a position where it works.  Go figure.

this.open = function(callback) {
console.log('opening device')
_device = usb.findByIds(0x132b, 0x2101);

_device.__open();
_device.__claimInterface(0);

_device.open();


_ifc = _device.interface();

_ifc.claim();

_wep = _ifc.endpoint(0x02);
_rep = _ifc.endpoint(0x82);

if (callback) callback(null, 'OK');
};


On Jan 8, 2015, at 12:01 AM, Jean-Thierry BONHOMME <notifications@github.com<mailto:notifications@github.com>> wrote:


Same issue for me:
OSX Lion 10.7.5

$  uname -a
Darwin new-host.home 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64
$  node -v
v0.10.33
$  npm -v
1.4.28

**Comment by jtbonhomme** [comment] 2015-01-10 07:35
Thanks, worked for me.
I added the following line in usb.js (line 26) in the <code>open</code> prototype after the <code>this.__open()</code> call (line 25):
```
	this.__claimInterface(0); 
````
 
and it solved the issue.

**Comment by jacobrosenthal** [comment] 2015-02-20 22:00
Same here, 10.9.5. 
node v0.10.36

**Comment by kevinmehall** [comment] 2015-02-27 01:02
I was finally able to reproduce this. If the device descriptor has the `bDeviceClass` field equal to 255 (Vendor Specific Class), OS X leaves the device unconfigured. If `bDeviceClass` is set to 0 (class defined at interface level), configuration 1 is set automatically.

`node-usb` does not currently wrap the `libusb_set_configuration` that can be used to change the device configuration, because most devices have a single configuration, but this is a use case where it proves necessary.

**Comment by cstyan** [comment] 2015-05-25 19:07
This error seems to be thrown inconsistently.  I can attach the device a few times without the error getting thrown, and later it will be thrown.  Sometimes I get an Error: LIBUSB_SUCCESS / LIBUSB_TRANSFER_COMPLETE thrown.  I am using the above workaround but still getting the same errors.

**Comment by DamonOehlman** [comment] 2016-04-20 06:16
Looks like this is still an issue for certain devices on MacOS.  Just had a go at updating my [skyportal](https://github.com/DamonOehlman/skyportal) to latest package version and test it on my OSX and it fell in a heap.  Interestingly, the fix suggested by @jtbonhomme around the use of `claimInterface(0)` fixed the problem in that case too.

**Comment by BonsoirDiep** [comment] 2016-11-20 06:22
win: __claimInterface() not run, please help me ...

**Comment by derMart** [comment] 2017-05-13 13:42
same error on windows :/
using 
-- usb@1.2.0
node v6.9.1

```
> usb.getDeviceList()[0].open();
Error: LIBUSB_ERROR_NOT_FOUND
    at Error (native)
    at Device.usb.Device.open ([...censored...]\node_modules\usb
\usb.js:33:7)
    at repl:1:24
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
```

is there any fix for this?

**Comment by jr-k** [comment] 2017-05-20 09:04
Same error ! Is there a fix ?

**Comment by kevinmehall** [comment] 2017-05-20 18:40
If you are on Windows, it is not the same problem. Make sure the WinUSB driver is bound to the device with a tool like Zadig.

Closing the macOS issue, as this library now provides the `device.open(false)`, `device.setConfiguration(1)` methods that allow you to tell the kernel to configure the device.

**Closed by kevinmehall** 2017-05-20 18:40 UTC

**Comment by jadonk** [comment] 2017-07-22 05:16
As far as I can tell, this still doesn't work.

```
device.open(false);
device.setConfiguration(2, function(err){console.log("Error");});
device.interface(1);
```

Generates:

`Error: Device must be open before searching for interfaces
`

**Comment by matthewharwood** [comment] 2017-09-21 23:11
@kevinmehall getting the same error as @jadonk Any update?

**Comment by thegecko** [comment] 2018-02-27 21:23
I see the same problem on a MacOS machine running 10.9 where the device descriptor has a `bDeviceClass` of 239. The 'open(false)...' fix doesn't resolve it, but it also doesn't error on MacOS 10.12, either.

**Comment by jounii** [comment] 2024-02-10 10:19
I stumbled on this ´bdeviceClass` of 255 on macOS. The ´open(false)` workaround works, but unfortunately not sure what would be the "correct" way to handle it with the WebUSB classes as there is no pre-initialize callback in the `WebUSBDevice.createInstance` for custom open procedures. Patching up the initialize function solves the problem, but without patching I see only option being using the usb part directly to first open the device (and filtering right one) before querying it again with requestDevice (problem is in loadDevices -> getWebDevice).
